import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['src/bin.ts'],
    splitting: true,
    sourcemap: true,
    clean: true,
    format: ['esm'],
    platform: 'node',
    tsconfig: './tsconfig.json',
    target: 'es2020',
    shims: false,
    dts: false,
    outExtension: () => ({ js: '.mjs' }),
  },
  {
    entry: ['src/index.ts'],
    splitting: false,
    sourcemap: true,
    clean: true,
    format: ['cjs', 'esm'],
    platform: 'node',
    tsconfig: './tsconfig.json',
    target: 'es2020',
    shims: false,
    dts: true,
    legacyOutput: true,
    onSuccess: `echo '{"type":"module"}' > dist/esm/package.json`,
  },
  {
    entry: ['src/adapters/fetch.ts', 'src/adapters/axios.ts'],
    splitting: true,
    sourcemap: true,
    clean: true,
    format: ['cjs', 'esm'],
    platform: 'node',
    tsconfig: './tsconfig.json',
    target: 'es2020',
    shims: false,
    dts: true,
    legacyOutput: true,
    outDir: './adapters',
    onSuccess: `echo '{"type":"module"}' > adapters/esm/package.json`,
  },
]);
